### ISSUE TITLE
First search result is always given in next searches, even on different engines

### ISSUE THREAD

**Issue by zakaryan2004** [bisoncorps/search-engine-parser#92]
**Describe the bug**
After doing a search once, the next searches always return the same result of the first one, both when the same or different search engine is used.

**To Reproduce**
1. Open python console
2. Import search_engine_parser
3. Initialize GoogleSearch()
4. Search keyword 'apple' (or anything else) using Google(or another) Engine
5. Print the results
6. Search keyword 'orange' (or anything different) using Google(or another, can be different from the first) Engine.
7. Print the results
8. Notice that the results are the same

**Code samples**
from search_engine_parser import GoogleSearch
google_search = GoogleSearch()
res_apple = google_search.search('apple', 1)
print(res_apple[0])
res_orange = google_search.search('orange', 1)
print(res_orange[0])

from search_engine_parser.core.engines.yahoo import Search as YahooSearch
from search_engine_parser.core.engines.google import Search as GoogleSearch2
yahoo_search = YahooSearch()
google_search_2 = GoogleSearch2()
res_banana = google_search_2.search('banana', 1)
print(res_banana[0])
res_apricot = yahoo_search.search('apricot', 1)
print(res_apricot[0])

**Expected behavior**
The search results should be different.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS on WSL2
 - Python Version: 3.6.9
 - Search-engine-parser version: 0.6

**Additional context**
The bug doesn't happen in version 0.5.4.

**Comment by zakaryan2004** [comment]
Also present on the latest source.

**Comment by MeNsaaH** [comment]
@zakaryan2004 Thanks for your issue, it has been fixed and a newer 0.61 will be deployed

**Comment by zakaryan2004** [comment]
I have fetched the latest commits from master and the issue still exists.

**Comment by MeNsaaH** [comment]
@zakaryan2004 you can try now with the latest HEAD.

**Comment by zakaryan2004** [comment]
Ok, now works.
